[package]
name = "c6ol-client-leptos"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
c6ol-core = { path = "../core" }
leptos = { version = "=0.7.0-rc1", features = ["csr"] }

[lints]
workspace = true
